// Generated by CoffeeScript 1.9.3
var express, router;

express = require("express");

router = express.Router();

router.get('/', function(req, res) {
  return res.render("index");
});

module.exports = router;
